#!/bin/bash
#    al-help-pipemenu - an Openbox pipemenu for displaying help files
#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
#    Borrowed with love by the ArchLabs Boys.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#	Renamed for Archlabs

HELP='    mbox-help-pipemenu an Openbox Pipe Menu for displaying help files
    It should normally be called from an openbox menu.

Options (usually passed from the menu):
    -h --help   show this message

    If mbox-help-pipemenu is called with no options (the usual method),
    it will output an xml openbox pipemenu displaying various help files,
    both online and on the system.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

MBOX_COMMON_LIBDIR='/usr/local/lib/mbox/common'

if ! . "$MBOX_COMMON_LIBDIR/include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source include.cfg in $MBOX_COMMON_LIBDIR" >&2
    exit 1
fi

menuStart
menuSeparator 'Manjaro Linux Online'
menuSeparator
menuItem 'Manjaro Homepage' 'exo-open "https://manjaro.org/"'
menuItem 'Manjaro Forum' 'exo-open "https://forum.manjaro.org/"'

menuSeparator

menuSubmenu 'OpenboxWWW' 'Openbox'
menuSubmenu 'ObWWW' 'Openbox Website'
menuItem 'Openbox Homepage' 'exo-open "http://openbox.org/"'
menuItem 'Openbox Getting Started' 'exo-open "http://openbox.org/wiki/Help:Getting_started"'
menuItem 'Openbox Documentation' 'exo-open "http://openbox.org/wiki/Help:Contents"'
menuItem 'Openbox FAQs' 'exo-open "http://openbox.org/wiki/Help:FAQ"'
menuSubmenuEnd
menuItem 'Arch Wiki Openbox Guide' 'exo-open "http://wiki.archlinux.org/index.php/Openbox"'
menuItem 'Debian Wiki Openbox Guide' 'exo-open "https://wiki.debian.org/Openbox"'
menuItem 'Urukramas Openbox Guide' 'exo-open "https://urukrama.wordpress.com/openbox-faq/"'
menuItem 'Openbox Reddit' 'exo-open "https://www.reddit.com/r/openbox/"'
menuSubmenuEnd

menuSubmenu 'Tint2WWW' 'Tint2'
menuItem 'Tint2 Wiki: FAQ' 'exo-open "https://gitlab.com/o9000/tint2/wikis/FAQ"'
menuItem 'Tint2 Wiki: Configuration' 'exo-open "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
menuItem 'Tint2 Forum Thread' 'exo-open "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
menuItem 'Tint2 Man Pages' 'urxvt -T "Tint2 man page" -e man tint2'
menuSubmenuEnd

menuSubmenu 'ConkyWWW' 'Conky'
menuItem 'Conky Wiki' 'exo-open "https://github.com/brndnmtthws/conky/wiki"'
menuItem 'Conky Archive' 'exo-open "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
menuItem 'Conky Reddit' 'exo-open "https://www.reddit.com/r/conky/"'
menuItem 'Conky Man Pages' 'urxvt -T "Conky man page" -e man conky'
menuSubmenuEnd
menuSeparator

menuSubmenu 'ThemesWWW' 'Theme Resources'
menuItem 'Bunsenlabs on DeviantArt' 'exo-open "http://bunsenlabs.deviantart.com/"'
menuItem 'Eye Candy Linux DeviantArt' 'exo-open "http://eye-candy-linux.deviantart.com/"'
menuItem 'Box-Look.org' 'exo-open "http://www.box-look.org"'
menuItem 'Gnome-Look.org' 'exo-open "http://gnome-look.org/"'
menuItem 'Eye Candy Linux Google+' 'exo-open "https://plus.google.com/u/0/communities/104794997718869399105"'
menuItem 'UnixPorn' 'exo-open "https://www.reddit.com/r/unixporn/"'
menuItem 'nixers.net' 'exo-open "http://nixers.net/"'
menuSubmenuEnd

menuSeparator 'Man Pages'
menuItem 'Compositor' 'termite -T "Compositor man page" -e man compton'
menuItem 'Dmenu' 'termite -T "dmenu man page" -e man dmenu'
menuItem 'Xrandr' 'termite -T "xrandr man page" -e man xrandr'
menuItem 'Yad' 'termite -T "yad man page" -e man yad'

menuSeparator 'Wikis'
menuItem 'Manjaro Wiki' 'exo-open "https://wiki.manjaro.org"'
menuItem 'Arch Wiki' 'exo-open "https://wiki.archlinux.org/index.php/Table_of_contents"'
menuItem 'Termite' 'exo-open "https://wiki.archlinux.org/index.php/termite"'

menuEnd

